traduction = {'cleanliness': 'pulizia',
              'comfort': 'comodo',
              'amenities': 'servizi',
              'staff': 'personale',
              'value': 'valore',
              'wifi': 'wifi',
              'location': 'posizione',
              'other': 'altro',
              'positive': 'positive',
              'negative': 'negative',
              'neutral': 'neutral',
              'mixed': 'mixed'}